---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: ibpcas.ibp.com
spec:
  group: ibp.com
  names:
    kind: IBPCA
    listKind: IBPCAList
    plural: ibpcas
    singular: ibpca
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: 'Certificate Authorities issue certificates for all the identities
          to transact on the network. Warning: CA deployment using this tile is not
          supported. Please use the IBP Console to deploy a CA.'
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: IBPCASpec defines the desired state of IBP CA
            properties:
              action:
                description: Action (Optional) is action object for trigerring actions
                properties:
                  renew:
                    description: Renew action is object for certificate renewals
                    properties:
                      tlscert:
                        description: TLSCert action is used to renew TLS crypto for
                          CA server
                        type: boolean
                    type: object
                  restart:
                    description: Restart action is used to restart the running CA
                    type: boolean
                type: object
              arch:
                description: Arch (Optional) is the architecture of the nodes where
                  CA should be deployed
                items:
                  type: string
                type: array
              configoverride:
                description: ConfigOverride (Optional) is the object to provide overrides
                  to CA & TLSCA config
                properties:
                  ca:
                    description: CA (Optional) is the overrides to CA's configuration
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  maxnamelength:
                    description: MaxNameLength (Optional) is the maximum length of
                      the name that the CA can have
                    type: integer
                  tlsca:
                    description: TLSCA (Optional) is the overrides to TLSCA's configuration
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              customNames:
                description: CustomNames (Optional) is to use pre-configured resources
                  for CA's deployment
                properties:
                  pvc:
                    description: PVC is the list of PVC Names to be used for CA's
                      deployment
                    properties:
                      ca:
                        description: CA is the pvc to be used as CA's storage
                        type: string
                    type: object
                  sqlitepath:
                    description: Sqlite is the sqlite path to be used for CA's deployment
                    type: string
                type: object
              domain:
                description: Domain is the sub-domain used for CA's deployment
                type: string
              hsm:
                description: HSM (Optional) is DEPRECATED
                properties:
                  pkcs11endpoint:
                    description: PKCS11Endpoint is DEPRECATED
                    type: string
                type: object
              imagePullSecrets:
                description: ImagePullSecrets (Optional) is the list of ImagePullSecrets
                  to be used for CA's deployment
                items:
                  type: string
                type: array
              images:
                description: Images (Optional) lists the images to be used for CA's
                  deployment
                properties:
                  caImage:
                    description: CAImage is the name of the CA image
                    type: string
                  caInitImage:
                    description: CAInitImage is the name of the Init image
                    type: string
                  caInitTag:
                    description: CAInitTag is the tag of the Init image
                    type: string
                  caTag:
                    description: CATag is the tag of the CA image
                    type: string
                  enrollerImage:
                    description: EnrollerImage is the name of the init image for crypto
                      generation
                    type: string
                  enrollerTag:
                    description: EnrollerTag is the tag of the init image for crypto
                      generation
                    type: string
                  hsmImage:
                    description: HSMImage is the name of the HSM image
                    type: string
                  hsmTag:
                    description: HSMTag is the tag of the HSM image
                    type: string
                type: object
              ingress:
                description: Ingress (Optional) is ingress object for ingress overrides
                properties:
                  class:
                    description: Class (Optional) is the class to set for ingress
                    type: string
                  tlsSecretName:
                    description: TlsSecretName (Optional) is the secret name to be
                      used for tls certificates
                    type: string
                type: object
              license:
                description: License should be accepted by the user to be able to
                  setup CA
                properties:
                  accept:
                    description: Accept should be set to true to accept the license.
                    enum:
                    - true
                    type: boolean
                type: object
              numSecondsWarningPeriod:
                description: NumSecondsWarningPeriod (Optional - default 30 days)
                  is used to define certificate expiry warning period.
                format: int64
                type: integer
              region:
                description: Region (Optional) is the region of the nodes where the
                  CA should be deployed
                type: string
              registryURL:
                description: RegistryURL is registry url used to pull images
                type: string
              replicas:
                description: Replicas (Optional - default 1) is the number of CA replicas
                  to be setup
                format: int32
                type: integer
              resources:
                description: Resources (Optional) is the amount of resources to be
                  provided to CA deployment
                properties:
                  ca:
                    description: CA is the resources provided to the CA container
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                  enrollJob:
                    description: EnrollJJob is the resources provided to the enroll
                      job container
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                  hsmDaemon:
                    description: HSMDaemon is the resources provided to the HSM daemon
                      container
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                  init:
                    description: Init is the resources provided to the init container
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                type: object
              service:
                description: Service (Optional) is the override object for CA's service
                properties:
                  type:
                    description: The "type" of the service to be used
                    type: string
                type: object
              storage:
                description: Storage (Optional - uses default storageclass if not
                  provided) is the override object for CA's PVC config
                properties:
                  ca:
                    description: CA is the configuration of the storage of the CA
                    properties:
                      class:
                        description: Class is the storage class
                        type: string
                      size:
                        description: Size of storage
                        type: string
                    type: object
                type: object
              version:
                description: FabricVersion (Optional) set the fabric version you want
                  to use.
                type: string
              zone:
                description: Zone (Optional) is the zone of the nodes where the CA
                  should be deployed
                type: string
            required:
            - license
            - version
            type: object
          status:
            description: Status is the observed state of IBPCA
            properties:
              errorcode:
                description: ErrorCode is the code of classification of errors
                type: integer
              lastHeartbeatTime:
                description: LastHeartbeatTime is when the controller reconciled this
                  component
                type: string
              message:
                description: Message provides a message for the status to be shown
                  to customer
                type: string
              reason:
                description: Reason provides a reason for an error
                type: string
              status:
                description: Status is defined based on the current status of the
                  component
                type: string
              type:
                description: Type is true or false based on if status is valid
                type: string
              version:
                description: Version is the product (IBP) version of the component
                type: string
              versions:
                description: Versions is the operand version of the component
                properties:
                  reconciled:
                    description: Reconciled provides the reconciled version of the
                      operand
                    type: string
                required:
                - reconciled
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
